# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecureMessanger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecureMessanger
  pod 'FlagPhoneNumber'
pod 'MessageKit'
pod 'Alamofire'
pod 'MBProgressHUD'
pod 'KeychainAccess'
pod 'SwiftyRSA', '1.6.0'
pod 'SDWebImage'
end
